### ISSUE TITLE
Teleporting players away

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#84]
I tried to teleport players away in combat with Skript and Essentials (/spawn , /tp etc..)

**Comment by Techcable** [comment]
Could you please [gist](https://gist.github.com/) your plugin.yml?

**Comment by christiaanbruijnes** [comment]
Ofcourse, however this is not the latest config because I am using a stable build since the newest still had these bugs.

https://gist.github.com/chrisbruijnes/0eb0eb46ba90cbca91b77b834130f4dc

I do had that config value on true about the teleporting thingy.

**Comment by christiaanbruijnes** [comment]
Bump

**Comment by Techcable** [comment]
Do players see the disabled teleportation message?

**Comment by christiaanbruijnes** [comment]
No, because I have that option on false.

**Comment by christiaanbruijnes** [comment]
Do you need more information?

**Comment by Byteflux** [comment]
You need to be running the latest builds available from the CI server. We can't help you with stable builds because we don't know whether the issue is present in the newer builds. A few changes have been made to teleportation behavior in recent builds that could affect it.

You may reopen this issue after you have tested it on the latest build and provided clear instructions on how to reproduce the issue.
